<a href="https://colab.research.google.com/github/viswambhari/ML-model/blob/main/final_ml_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re
import sklearn
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [ ]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords


In [ ]:
news_data= pd.read_csv("/content/train.csv")

In [ ]:
news_data.shape

(20800, 5)

In [ ]:
news_data.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
# fake news- 0
#real-news- 1

In [ ]:
news_data.isnull().sum() 
#prints missing values

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
news_data=news_data.fillna(' ') # replacing missing values with 0 and  1

In [ ]:
news_data.isnull().sum() #no missing values found

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
news_data['content']= news_data['title']+ ' '+ news_data['author']#combining title and author as one colun calleld content

In [ ]:
print(news_data['content'])

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2        Why the Truth Might Get You Fired Consortiumne...
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799              What Keeps the F-35 Alive David Swanson
Name: content, Length: 20800, dtype: object


In [ ]:
X= news_data.drop(columns="label",axis=1)#data without the label 
Y=news_data['label']#just the label

In [ ]:
print(X)
print(Y)

          id  ...                                            content
0          0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  ...  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2          2  ...  Why the Truth Might Get You Fired Consortiumne...
3          3  ...  15 Civilians Killed In Single US Airstrike Hav...
4          4  ...  Iranian woman jailed for fictional unpublished...
...      ...  ...                                                ...
20795  20795  ...  Rapper T.I.: Trump a ’Poster Child For White S...
20796  20796  ...  N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797  20797  ...  Macy’s Is Said to Receive Takeover Approach by...
20798  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799  ...            What Keeps the F-35 Alive David Swanson

[20800 rows x 5 columns]
0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 2080

In [ ]:
port_stem=PorterStemmer()

In [ ]:
#def stemming(content):
 # stemmed_content=re.sub('^a-zA-Z', '  ',content) #remove numbers and punctuations
  #stemmed_content= stemmed_content.lower()
  #stemmed_content= stemmed_content.split()
  #stemmed_content=[port_stem.stem(word) for word in stemmed_content if word not in stopwords.words('english')]
  #stemmed_content=' '.join(stemmed_content)
  #return stemmed_content

In [ ]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [ ]:
news_data['content']=news_data['content'].apply(stemming)

In [ ]:
print (news_data['content'])

0        hous dem aid even see comey letter jason chaff...
1        flynn hillari clinton big woman campu breitbar...
2                   truth might get fire consortiumnew com
3        civilian kill singl us airstrik identifi jessi...
4        iranian woman jail fiction unpublish stori wom...
                               ...                        
20795    rapper trump poster child white supremaci jero...
20796    n f l playoff schedul matchup odd new york tim...
20797    maci said receiv takeov approach hudson bay ne...
20798    nato russia hold parallel exercis balkan alex ...
20799                            keep f aliv david swanson
Name: content, Length: 20800, dtype: object


In [ ]:
#separating the data and label
X = news_data['content'].values
Y = news_data['label'].values

In [ ]:
print(X)

['hous dem aid even see comey letter jason chaffetz tweet darrel lucu'
 'flynn hillari clinton big woman campu breitbart daniel j flynn'
 'truth might get fire consortiumnew com' ...
 'maci said receiv takeov approach hudson bay new york time michael j de la merc rachel abram'
 'nato russia hold parallel exercis balkan alex ansari'
 'keep f aliv david swanson']


In [ ]:
print (Y)

[1 0 1 ... 0 1 1]


In [ ]:
Y.shape


(20800,)

In [ ]:
#convert text into numerical
vectorizer = TfidfVectorizer()
vectorizer.fit(X)#fitting the data
X = vectorizer.transform(X)#transforming it into numbers

In [ ]:
print(X)

  (0, 15686)	0.28485063562728646
  (0, 13473)	0.2565896679337957
  (0, 8909)	0.3635963806326075
  (0, 8630)	0.29212514087043684
  (0, 7692)	0.24785219520671603
  (0, 7005)	0.21874169089359144
  (0, 4973)	0.233316966909351
  (0, 3792)	0.2705332480845492
  (0, 3600)	0.3598939188262559
  (0, 2959)	0.2468450128533713
  (0, 2483)	0.3676519686797209
  (0, 267)	0.27010124977708766
  (1, 16799)	0.30071745655510157
  (1, 6816)	0.1904660198296849
  (1, 5503)	0.7143299355715573
  (1, 3568)	0.26373768806048464
  (1, 2813)	0.19094574062359204
  (1, 2223)	0.3827320386859759
  (1, 1894)	0.15521974226349364
  (1, 1497)	0.2939891562094648
  (2, 15611)	0.41544962664721613
  (2, 9620)	0.49351492943649944
  (2, 5968)	0.3474613386728292
  (2, 5389)	0.3866530551182615
  (2, 3103)	0.46097489583229645
  :	:
  (20797, 13122)	0.2482526352197606
  (20797, 12344)	0.27263457663336677
  (20797, 12138)	0.24778257724396507
  (20797, 10306)	0.08038079000566466
  (20797, 9588)	0.174553480255222
  (20797, 9518)	0.295420

splitting data into two datsets


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2, stratify=Y)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
#training data accuracy

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [ ]:
print(training_data_accuracy)

0.9865985576923076


In [ ]:
#testing data accuracy


In [ ]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
print(test_data_accuracy)

0.9790865384615385


In [ ]:

x_new = x_test[5]
prediction = model.predict(x_new)
print(prediction)
if (prediction[0]==0):
  print('The news is Real')
else:
  print('The news is Fake')

[1]
The news is Fake


In [ ]:
from nltk.corpus import stopwords
stop_words=stopwords.words('english')
news_data['inlower']=news_data['content'].apply(lambda x:" ".join(word.lower() for word in x.split()))
news_data['punctuations']=news_data['inlower'].str.replace('[^\w\s]','')
news_data['stopwords']=news_data['punctuations'].apply(lambda x:" ".join(word for word in x.split() if word not in stop_words))
from textblob import Word 
import nltk
nltk.download('wordnet')
news_data['lemmatized']=news_data['stopwords'].apply(lambda x:" ".join(Word(word).lemmatize() for word in x.split()))
from textblob import TextBlob
news_data['polarity']=news_data['lemmatized'].apply(lambda x:TextBlob(x).sentiment[0])
news_data['subjectivity']=news_data['lemmatized'].apply(lambda x:TextBlob(x).sentiment[1])


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
news_data.head()

id  ... subjectivity
0   0  ...          0.0
1   1  ...          0.1
2   2  ...          0.0
3   3  ...          0.0
4   4  ...          0.0

[5 rows x 12 columns]

In [ ]:
x_new = x_test[3]

prediction = model.predict(x_new)
print(prediction)

if (prediction==0):
  print('The news is Real')
else:
  print('The news is Fake')

[0]
The news is Real


In [ ]:
import pickle
pickle.dump(model, open('model2.pkl', 'wb'))
pickle.dump(vectorizer, open('tfidfvect2.pkl', 'wb'))

In [ ]:
stemmed_content = re.sub('[^a-zA-Z]',' ','content')
stemmed_content = stemmed_content.lower()
stemmed_content = stemmed_content.split()
stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
stemmed_content = ' '.join(stemmed_content)
val = vectorizer.transform([stemmed_content]).toarray()
model.predict(val)


array([1])

In [ ]:
joblib_model = pickle.load(open('model2.pkl', 'rb'))
joblib_vect = pickle.load(open('tfidfvect2.pkl', 'rb'))
val_pkl = joblib_vect.transform([stemmed_content]).toarray()
joblib_model.predict(val_pkl)

array([1])